name: Documentation

on: [push, pull_request]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: docs/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html/
