name: Documentation

on: [push, pull_request]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: 'docs/'
